name: Build Nextron App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Set GitHub token
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Import Code Signing Certificates
        env:
          APPLE_DEVELOPER_CERTIFICATE_P12_BASE64: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_P12_BASE64 }}
          APPLE_DEVELOPER_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_PASSWORD }}
        run: |
          echo "$APPLE_DEVELOPER_CERTIFICATE_P12_BASE64" | base64 --decode > certificate.p12
          security create-keychain -p actions macos-build.keychain
          security default-keychain -s macos-build.keychain
          security unlock-keychain -p actions macos-build.keychain
          security import certificate.p12 -k macos-build.keychain -P "$APPLE_DEVELOPER_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k actions macos-build.keychain

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build Nextron App
        run: npm run build:mac:universal
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: "false"
          APPLE_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Staff Time Tracker - Mac
          path: |
            dist/*.dmg
          retention-days: 5

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Set GitHub token
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build Nextron App
        run: npm run build:win
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Staff Time Tracker - Windows
          path: |
            dist/*.exe
          retention-days: 5

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Set GitHub token
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Install snapcraft
        run: |
          sudo snap install snapcraft --classic
      - name: Build Nextron App
        run: npm run build:linux
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Staff Time Tracker - Linux
          path: |
            dist/*.AppImage
          retention-days: 5
